#############################################################################
# Makefile for building: beBetterThanCV
# Generated by qmake (3.1) (Qt 6.7.2)
# Project:  beBetterThanCV.pro
# Template: app
# Command: /usr/sbin/qmake6 -o Makefile beBetterThanCV.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I/usr/include/opencv4/opencv2 -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/sbin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/sbin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/sbin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = beBetterThanCV1.0.0
DISTDIR = /mnt/c/Users/archLinux/Documents/beBetterThanCV/.tmp/beBetterThanCV1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lopencv_core -lopenh -lopenv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_videoio   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		beBetterThanCV.pro  main.cpp
QMAKE_TARGET  = beBetterThanCV
DESTDIR       = 
TARGET        = beBetterThanCV


first: all
####### Build rules

beBetterThanCV:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: beBetterThanCV.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		beBetterThanCV.pro
	$(QMAKE) -o Makefile beBetterThanCV.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
beBetterThanCV.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile beBetterThanCV.pro

qmake_all: FORCE


all: Makefile beBetterThanCV

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

